---
credentials:
  rmq_port:   5672
  mgmt_port: 15672
  hosts:    (( grab jobs.node.ips ))
  username: (( grab meta.username ))
  password: (( grab meta.password ))
  uris:     (( cartesian-product "amqp://" meta.username ":" meta.password "@" jobs.node.ips ":" credentials.rmq_port ))
  uri:      (( grab credentials.uris[0] ))
  hostnames: (( grab jobs.node.ips ))
  hostname: (( grab credentials.hostnames[0] ))
  protocols:
    amqp:
      hosts: (( grab jobs.node.ips ))
      host: (( grab credentials.hosts[0] ))
      password: (( grab meta.password ))
      port: 5672
      ssl: false
      uris: (( grab credentials.uris ))
      uri:  (( grab credentials.uris[0] ))
      username: (( grab meta.username ))
